Attempt custom badges

diff --git a/.github/workflows/kernel-5.8.yml b/.github/workflows/kernel-5.8.yml
--- a/.github/workflows/kernel-5.8.yml
+++ b/.github/workflows/kernel-5.8.yml
@@ -1,6 +1,10 @@
-name: 5.8
+name: "5.8"
 
-on: [push]
+on:
+  push:
+    branches:
+    - '*'
+    - '!badges'
 
 jobs:
 
@@ -29,5 +33,59 @@ jobs:
       run: |
         if ! command -v nixmodule; then cargo install nixmodule; fi; \
         if [ $(printf '%s\n' $(nixmodule -V | cut -d " " -f 2) "0.4.0" | sort -V | head -n1) != "0.4.0" ]; then cargo install -f nixmodule; fi
+
+    # Get current banch name to use it as dest directory
+    - name: Extract branch name
+      shell: bash
+      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+      id: extract_branch
+
+    # Run the test and obtain badge results via exit code
     - name: Perform the test
-      run: cd module && NIXMODULEARGS="-k 5.8. -c ci-config.toml" ./tests/run.sh
+      id: run
+      run: |
+        echo "Default badge settings..."; \
+        echo "##[set-output name=build;]'N/A'" && echo "##[set-output name=buildc;]'grey'"; \
+        echo "##[set-output name=insmod;]'N/A'" && echo "##[set-output name=insmodc;]'grey'"; \
+        echo "##[set-output name=test;]'N/A'" && echo "##[set-output name=testc;]'grey'"; \
+        cd module; NIXMODULEARGS="-k 5.8. -c ci-config.toml" ./tests/run.sh; code=$?; \
+        echo "Exited with $code"; \
+        if [ $code == 0 ]; then build=1 && insmod=1 && test=1; fi; \
+        if [ $code == 4 ]; then build=0; fi; \
+        if [ $code == 5 ]; then build=1 && insmod=0; fi; \
+        if [ $code == 6 ]; then build=1 && insmod=1 && test=0; fi; \
+        echo "Set build=$build insmod=$insmod test=$insmod"; \
+        if [ $build == 1 ]; then echo "##[set-output name=build;]'Passing'" && echo "##[set-output name=buildc;]'green'"; fi; \
+        if [ $insmod == 1 ]; then echo "##[set-output name=insmod;]'Passing'" && echo "##[set-output name=insmodc;]'green'"; fi; \
+        if [ $test == 1 ]; then echo "##[set-output name=test;]'Passing'" && echo "##[set-output name=testc;]'green'"; fi;
+        if [ $build == 0 ]; then echo "##[set-output name=build;]'Failed'" && echo "##[set-output name=buildc;]'red'"; fi; \
+        if [ $insmod == 0 ]; then echo "##[set-output name=insmod;]'Failed'" && echo "##[set-output name=insmodc;]'red'"; fi; \
+        if [ $test == 0 ]; then echo "##[set-output name=test;]'Failed'" && echo "##[set-output name=testc;]'red'"; fi;
+
+    # Generate the badge
+    - name: Build badge
+      uses: emibcn/badge-action@v1.2.1
+      with:
+        label: 'Build'
+        status: ${{ steps.run.outputs.build }}
+        color: ${{ steps.run.outputs.buildc }}
+        path: ${{ steps.extract_branch.outputs.branch }}/build-${{ name }}-badge.svg
+
+    # Checkout the badges branch
+    - uses: actions/checkout@v1
+      with:
+        ref: badges
+
+    # Create the directory where badges will be saved, if needed
+    - name: Create destination directory
+      env:
+        BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}
+      run: mkdir -p "${BADGE_PATH%/*}"
+
+    # Upload the badge as an artifact
+    - name: Upload badge as artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: build-${{ name }}-badge.svg
+        path: ${{ steps.extract_branch.outputs.branch }}/build-${{ name }}-badge.svg
+        if-no-files-found: error
