Update pull_request.yml

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -14,10 +14,10 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - id: run_test
-        uses: composite/test
+        uses: composite/test@latest
         with:
           kernel: ${{ matrix.version }}
 
-    # Pass/Fail based on original test exit code
-    - name: Exit
-      run: exit ${{ steps.run.outputs.realexit }}
+      # Pass/Fail based on original test exit code
+      - name: Exit
+        run: exit ${{ steps.run_test.outputs.exit-code }}
